In [9]:
import numpy as np

In [10]:
a=np.array([1,2,3])

In [11]:
a

array([1, 2, 3])

In [12]:
a=np.array([3,4,5,6,])

In [13]:
a

array([3, 4, 5, 6])

In [14]:
# creating a numpy with 5 arrays
c=np.array([1,2,3,4,5])

In [15]:
c

array([1, 2, 3, 4, 5])

In [16]:
# creating a numpy with 10 arrays
d=np.array([1,2,3,4,5,6,7,8,9,10])

In [17]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
c.shape

(5,)

In [19]:
c.ndim

1

In [20]:
d.shape

(10,)

In [21]:
d.ndim

1

In [22]:
e=np.array([[1,2],[3,4]])

In [23]:
e

array([[1, 2],
       [3, 4]])

In [24]:
e.shape

(2, 2)

In [25]:
e.ndim

2

In [26]:
f=np.array([[1,2,3],[4,5,6]])

In [27]:
f

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
d[2]           #indexing

np.int64(3)

In [30]:
d[2:7]        #slicing

array([3, 4, 5, 6, 7])

In [31]:
x=np.array([1,2,3,4,5,])
x

array([1, 2, 3, 4, 5])

In [32]:
y=np. array([6,7,8,9,10])
y

array([ 6,  7,  8,  9, 10])

In [33]:
#addition
x+y

array([ 7,  9, 11, 13, 15])

In [34]:
x-y

array([-5, -5, -5, -5, -5])

In [35]:
#multiplication
x*y

array([ 6, 14, 24, 36, 50])

In [36]:
#division
x/y

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [37]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [38]:
#exponential     value-2.718
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [40]:
2.718**5 

148.33623849186557

In [59]:
z=np.arange(12)

In [65]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
z.shape

(12,)

In [67]:
z.dtype

dtype('int64')

In [68]:
z.ndim

1

In [70]:
w=z.reshape((3,4))

In [71]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
#checking shape
w.shape

(3, 4)

In [73]:
#checking data type
w.dtype

dtype('int64')

In [74]:
#checking dimention
w.ndim

2